/*
    INSERT: single row, multi row, INSERT ... SELECT and OUTPUT.
*/

USE SqlRecipes;
GO

/* Always name the target columns. Column order in the table can change. */
INSERT INTO dbo.Categories (Name, Description)
VALUES (N'Garden', N'Gardening tools and supplies');
GO

/* A single statement inserting several rows is one transaction and one log flush. */
INSERT INTO dbo.Categories (Name, Description)
VALUES
    (N'Toys',      N'Games and toys'),
    (N'Groceries', N'Food and beverages');
GO

/* OUTPUT returns the generated keys without a second round trip. */
DECLARE @Inserted TABLE (CategoryId INT, Name NVARCHAR(120));

INSERT INTO dbo.Categories (Name, Description)
OUTPUT inserted.CategoryId, inserted.Name INTO @Inserted
VALUES (N'Pet Supplies', N'Everything for pets');

SELECT * FROM @Inserted;
GO

/* INSERT ... SELECT copies rows from a query. */
CREATE TABLE #ExpensiveProducts
(
    ProductId INT            NOT NULL,
    Name      NVARCHAR(160)  NOT NULL,
    UnitPrice DECIMAL(18, 2) NOT NULL
);

INSERT INTO #ExpensiveProducts (ProductId, Name, UnitPrice)
SELECT p.ProductId, p.Name, p.UnitPrice
FROM dbo.Products AS p
WHERE p.UnitPrice > 1000.00;

SELECT COUNT(*) AS CopiedRows FROM #ExpensiveProducts;

DROP TABLE #ExpensiveProducts;
GO

/* SCOPE_IDENTITY returns the last identity generated in the current scope.
   @@IDENTITY crosses scopes and can return a value generated by a trigger. */
INSERT INTO dbo.Categories (Name, Description)
VALUES (N'Automotive', N'Car parts and accessories');

SELECT SCOPE_IDENTITY() AS NewCategoryId;
GO

/* Clean up the rows created by this script. */
DELETE FROM dbo.Categories
WHERE Name IN (N'Garden', N'Toys', N'Groceries', N'Pet Supplies', N'Automotive');
GO
